#+STARTUP: overview

* Lentil tabbouleh
:PROPERTIES:
:Cantidad: 4 personas
:Tiempo: 1 hora
:Vegan: yes
:Fuente: https://www.jamieoliver.com/recipes/vegetables-recipes/lentil-tabbouleh/
:END:

** Ingredientes

|   200 | g           | puy lentils                |
|     1 | bunch       | of spring onions           |
|   200 | g           | ripe cherry tomatoes       |
|     1 | large bunch | of fresh flat-leaf parsley |
|     1 | large bunch | of fresh mint              |
| extra |             | virgin olive oil           |
|     1 |             | lemon                      |


** Method
   1. Rinse the lentils, then cook in plenty of salted water until tender. Drain and set aside to cool.
   1. Trim and finely slice the spring onions, halve the tomatoes, then pick and finely chop the herb leaves.
   1. Mix the cooled lentils with the spring onions, tomatoes, herbs and 4 tablespoons of oil. Add the lemon juice to taste, season with sea salt and black pepper, then serve.



* Pizza
:PROPERTIES:
:Cantidad: 4 personas
:Vegan: no
:Fuente: https://www.jamieoliver.com/recipes/recipe/pizza-dough/
:END:

** Ingredients

| 500 | g           | white bread flour or Tipo '00' flour |
| 100 | g           | finely ground semolina flour         |
| 1/2 | teaspoon    | fine sea saltx                       |
|   7 | g           | dried yeast sachets                  |
| 1/2 | tablespoon  | golden caster sugar                  |
|   1 | tablespoons | extra virgin olive oil               |


** Method
1. Sieve the flour/s and salt on to a clean work surface and make a well in the middle.
2. In a jug, mix the yeast, sugar and oil into 650ml of lukewarm water and leave for a few minutes, then pour into the well.
3. Using a fork, bring the flour in gradually from the sides and swirl it into the liquid. 
4. Keep mixing, drawing larger amounts of flour in, and when it all starts to come together, work the rest of the flour in with your clean, flour-dusted hands. Knead until you have a smooth, springy dough.
7. Place the ball of dough in a large flour-dusted bowl and flour the top of it. Cover the bowl with a damp cloth and place in a warm room for about an hour until the dough has doubled in size.
8. Now remove the dough to a flour-dusted surface and knead it around a bit to push the air out with your hands – this is called knocking back the dough. You can either use it immediately, or keep it, wrapped in clingfilm, in the fridge (or freezer) until required.
9. If using straight away, divide the dough up into as many little balls as you want to make pizzas – this amount of dough is enough to make about six to eight medium pizzas.
10. Timing-wise, it’s a good idea to roll the pizzas out about 15 to 20 minutes before you want to cook them. Don’t roll them out and leave them hanging around for a few hours, though – if you are working in advance like this it’s better to leave your dough, covered with clingfilm, in the fridge. However, if you want to get them rolled out so there’s one less thing to do when your guests are round, simply roll the dough out into rough circles, about 0.5cm thick, and place them on slightly larger pieces of olive-oil-rubbed and flour-dusted tin foil. You can then stack the pizzas, cover them with clingfilm, and pop them into the fridge.


* Naan bread
:PROPERTIES:
:Cantidad: 6 personas
:Tiempo: 1.5 horas
:Vegan: no
:Fuente: http://www.taste.com.au/recipes/naan-bread/7d5c1635-6597-48a6-8fe1-4dff038c9cff
:END:

** Ingredients
| 450 | g                     | bread flour                      |
|   7 | g                     | dried yeast                      |
|   1 | teaspoon salt         |                                  |
|   1 | teaspoon caster sugar |                                  |
| 185 | ml                    | warm water                       |
|   6 | tablespoons           | Tamar Valley Greek Style Yoghurt |
|   2 | tablespoons           | vegetable oil                    |
|  30 | g                     | ghee, melted                     |
|     |                       | Sesame seeds, toasted            |


** Method
1. Combine the flour, yeast, salt and sugar in a bowl. Mix in water, yoghurt and oil. Knead dough for 5 minutes or until smooth.
2. Place dough in a bowl. Cover with plastic wrap and set aside in a warm place for 1 hour or until the dough has doubled in size.
3. Meanwhile, preheat oven to 250°C. Preheat pizza stone for 40 minutes. Punch down dough then divide it into 6 portions.
4. Roll out each portion of dough on a lightly floured surface into a 12 x 20cm oval shape.
5. Spray both sides of the dough with oil. Bake on pizza stone for 5 minutes or until puffed and light golden.
6. Brush with ghee and top with sesame seeds. Wrap in foil to keep warm. Repeat with the remaining dough.



* Cheescake
:PROPERTIES:
:Cantidad: 8 personas
:Tiempo: 1.5 horas
:Vegan: no
:Fuente: 
:END:

** Ingredientes

Crust

| 1 1/2 | cups       | all-purpose flour        |
|     1 | teaspoon   | baking powder            |
|       | pinch      | salt                     |
|     2 | teaspoons  | vanilla-sugar            |
|     1 | tablespoon | finely grated lemon rind |
|     1 |            | egg                      |
|   1/4 | cup        | granulated sugar         |
|   100 | g          | butter                   |

Filling

|     3 |            | egg yolks                 |
|   3/4 | cup        | granulated sugar          |
|     2 | teaspoons  | vanilla-sugar             |
|   100 | g          | butter (room temperature) |
|   170 | g          | creame                    |
|   500 | g          | creame cheese             |
| 1 1/2 | tablespoon | cornstarch                |
|     3 |            | egg whites                |
|       | pinch      | salt                      |

** Method

*** Crust
1. Stift the flour, stir in the baking powder, salt, vanilla-sugar,
   lemon peel and sugar.
2. Rub in the butter and knead to a smooth consistency with the egg.
3. Place dough in a plastic bag in the refrigerator for 1 hour.
4. Preheat oven to 150 C.
5. Roll out the dough on a well-floured work surface
6. Form it into a ball again and roll it out a second time
7. Place dough in bottom of a 22 - 24 cm springform, pressing it to
   the sides

*** Filling
1. Beat the egg yolks with the sugar and vanilla-sugar until pale and foamy.
2. Add the softened butter and beat well.
3. Add the heavy cream and beat again.
4. Add teh quark and stirr until the mixture is  smooth and throughly combined.

5. Whisk teh egg whites with the salt until very stiff.
6. Very gently fold in the cream cheese mixture, also adding the
   sifted cornstarch a little at a time.
7. Pour the filling into the crust shell and gently wobble the pan
   back and forth until the surface is smooth.
8. Trim the dough leaving about 2 cm .
9. Bake in preheated 150 C oven for 50 to 60 minutes.


