#+STARTUP: overview

* Lentil tabbouleh
:PROPERTIES:
:Cantidad: 4 personas
:Tiempo: 1 hora
:Vegan: yes
:Fuente: https://www.jamieoliver.com/recipes/vegetables-recipes/lentil-tabbouleh/
:END:

** Ingredientes

|   200 | g           | puy lentils                |
|     1 | bunch       | of spring onions           |
|   200 | g           | ripe cherry tomatoes       |
|     1 | large bunch | of fresh flat-leaf parsley |
|     1 | large bunch | of fresh mint              |
| extra |             | virgin olive oil           |
|     1 |             | lemon                      |


** Method
   1. Rinse the lentils, then cook in plenty of salted water until tender. Drain and set aside to cool.
   1. Trim and finely slice the spring onions, halve the tomatoes, then pick and finely chop the herb leaves.
   1. Mix the cooled lentils with the spring onions, tomatoes, herbs and 4 tablespoons of oil. Add the lemon juice to taste, season with sea salt and black pepper, then serve.



* Pizza
:PROPERTIES:
:Cantidad: 4 personas
:Vegan: no
:Fuente: https://www.jamieoliver.com/recipes/recipe/pizza-dough/
:END:

** Ingredients

| 400 | g           | white bread flour or Tipo '00' flour |
| 100 | g           | finely ground semolina flour         |
| 1/2 | teaspoon    | fine sea saltx                       |
|   7 | g           | dried yeast sachets                  |
| 1/2 | tablespoon  | golden caster sugar                  |
|   1 | tablespoons | extra virgin olive oil               |


** Method

1. Sieve the flour/s and salt on to a clean work surface and make a
   well in the middle.

2. In a jug, mix the yeast, sugar and oil into 325ml of lukewarm water
   and leave for a few minutes, then pour into the well.

3. Using a fork, bring the flour in gradually from the sides and swirl
   it into the liquid. 

4. Keep mixing, drawing larger amounts of flour in, and when it all
   starts to come together, work the rest of the flour in with your
   clean, flour-dusted hands. Knead until you have a smooth, springy
   dough.

7. Place the ball of dough in a large flour-dusted bowl and flour the
   top of it. Cover the bowl with a damp cloth and place in a warm
   room for about an hour until the dough has doubled in size.

8. Now remove the dough to a flour-dusted surface and knead it around
   a bit to push the air out with your hands – this is called knocking
   back the dough. You can either use it immediately, or keep it,
   wrapped in clingfilm, in the fridge (or freezer) until required.

9. If using straight away, divide the dough up into as many little
   balls as you want to make pizzas – this amount of dough is enough
   to make about six to eight medium pizzas.

10. Timing-wise, it’s a good idea to roll the pizzas out about 15 to
    20 minutes before you want to cook them. Don’t roll them out and
    leave them hanging around for a few hours, though – if you are
    working in advance like this it’s better to leave your dough,
    covered with clingfilm, in the fridge. However, if you want to get
    them rolled out so there’s one less thing to do when your guests
    are round, simply roll the dough out into rough circles, about
    0.5cm thick, and place them on slightly larger pieces of
    olive-oil-rubbed and flour-dusted tin foil. You can then stack the
    pizzas, cover them with clingfilm, and pop them into the fridge.


* Naan bread
:PROPERTIES:
:Cantidad: 6 personas
:Tiempo: 1.5 horas
:Vegan: no
:Fuente: http://www.taste.com.au/recipes/naan-bread/7d5c1635-6597-48a6-8fe1-4dff038c9cff
:END:

** Ingredients
| 450 | g                     | bread flour                      |
|   7 | g                     | dried yeast                      |
|   1 | teaspoon salt         |                                  |
|   1 | teaspoon caster sugar |                                  |
| 185 | ml                    | warm water                       |
|   6 | tablespoons           | Tamar Valley Greek Style Yoghurt |
|   2 | tablespoons           | vegetable oil                    |
|  30 | g                     | ghee, melted                     |
|     |                       | Sesame seeds, toasted            |


** Method
1. Combine the flour, yeast, salt and sugar in a bowl. Mix in water, yoghurt and oil. Knead dough for 5 minutes or until smooth.
2. Place dough in a bowl. Cover with plastic wrap and set aside in a warm place for 1 hour or until the dough has doubled in size.
3. Meanwhile, preheat oven to 250°C. Preheat pizza stone for 40 minutes. Punch down dough then divide it into 6 portions.
4. Roll out each portion of dough on a lightly floured surface into a 12 x 20cm oval shape.
5. Spray both sides of the dough with oil. Bake on pizza stone for 5 minutes or until puffed and light golden.
6. Brush with ghee and top with sesame seeds. Wrap in foil to keep warm. Repeat with the remaining dough.



* Cheescake
:PROPERTIES:
:Cantidad: 8 personas
:Tiempo: 1.5 horas
:Vegan: no
:Fuente: 
:END:

** Ingredientes

Crust

| 1 1/2 | cups       | all-purpose flour        |
|     1 | teaspoon   | baking powder            |
|       | pinch      | salt                     |
|     2 | teaspoons  | vanilla-sugar            |
|     1 | tablespoon | finely grated lemon rind |
|     1 |            | egg                      |
|   1/4 | cup        | granulated sugar         |
|   100 | g          | butter                   |

Filling

|     3 |            | egg yolks                 |
|   3/4 | cup        | granulated sugar          |
|     2 | teaspoons  | vanilla-sugar             |
|   100 | g          | butter (room temperature) |
|   170 | g          | creame                    |
|   500 | g          | creame cheese             |
| 1 1/2 | tablespoon | cornstarch                |
|     3 |            | egg whites                |
|       | pinch      | salt                      |

** Method

*** Crust
1. Stift the flour, stir in the baking powder, salt, vanilla-sugar,
   lemon peel and sugar.
2. Rub in the butter and knead to a smooth consistency with the egg.
3. Place dough in a plastic bag in the refrigerator for 1 hour.
4. Preheat oven to 150 C.
5. Roll out the dough on a well-floured work surface
6. Form it into a ball again and roll it out a second time
7. Place dough in bottom of a 22 - 24 cm springform, pressing it to
   the sides

*** Filling
1. Beat the egg yolks with the sugar and vanilla-sugar until pale and foamy.
2. Add the softened butter and beat well.
3. Add the heavy cream and beat again.
4. Add teh quark and stirr until the mixture is  smooth and throughly combined.

5. Whisk teh egg whites with the salt until very stiff.
6. Very gently fold in the cream cheese mixture, also adding the
   sifted cornstarch a little at a time.
7. Pour the filling into the crust shell and gently wobble the pan
   back and forth until the surface is smooth.
8. Trim the dough leaving about 2 cm .
9. Bake in preheated 150 C oven for 50 to 60 minutes.


* Sushi rice
:PROPERTIES:
:Fuente: http://www.wikihow.com/Make-Sushi-Rice
:END:

** Ingredientes

| 2 2/3 | cups | sushi rice or short-grain rice |
| 2 1/2 | cups | water                          |
| 3     | tbs. | rice vinegar                   |
| 2     | tbs. | sugar                          |
| 1 1/2 | tsp. | salt                           |

** Method

*** Measure out the rice. 

Depending on how hungry you are, if there are appetizers,
deserts, whatever, 600 grams (1.32 pounds) should be adequate for
four adults, if your meal includes an appetizer and perhaps
something for dessert. 600 grams is also often a very good portion
for your regular-sized stove pot, in that you get about a
half-filled pot of rice which seems to give the best result,
moisture and texture wise. A rice cooker is the most dependable
way of making rice.

*** Rinse and soak the rice. 

One way to do this is by finding a really big pot that you can fill
with lots of cold water. Rinse the rice by pouring lots of cold water
onto it, then use your hands to move the rice about in the water bath
so that it gives off as much as possible of those little dirt and
starch particles that make the water all greyish. You don't have to do
it very long, just give everything a good tumbling, then pour the
water out again, as much as possible. Alternatively, you can put the
rice in a strainer and put the strainer in the pot; fill the pot with
water, agitate the rice, then lift the strainer out of the pot so you
can pour out the milky water. Do this some four or five times, until
the water seems relatively clear. After the last rinse, pour fresh
water over the rice one last time and leave it to soak for about half
an hour. Some sources recommend letting the rice sit, drained, for
thirty minutes to an hour.

*** To boil

You'll need 100 milliliters of cold water for every 100 grams of
rice - that is, the weight of the rice before you let it soak, which
in this example would mean 600 milliliters (20.3 fl.oz.) of water as
we started out with 600 grams (21.2 oz) of rice. Whatever container
you used to measure out the rice, use the same to measure out the
water. Put the water with the rice in a pot or rice cooker, put on the
lid (not to remove it again until the rice is done), and you turn up
the heat to high. If you are using a rice cooker, let it do its thing;
skip the next two steps, and go straight to cooling the rice (once the
rice has finished cooking, of course). There is also the possibility
of making sushi rice in the oven, as described in the section
below. Otherwise...

***  Watch over the pot until it starts to boil. 

You'd really prefer a pot with a glass lid here, so that you can see
the bubbles, because removing the lid would let out the steam and
interfere with the cooking process. Once it starts boiling, start your
timer. You want seven minutes to pass with full heat under the
pot. You'll think "Oh no, it's gonna burn in the bottom" and you're
partly right - some of the rice will stick to the bottom, but that's
fine, because we won't be using that rice for the sushi anyway. It's
inevitable that some of the rice will stick to the bottom, but some
seeds will have to die for the rest of them to be perfect.

Don't use a pot or rice cooker with Teflon or some other type of
non-stick coating inside. We want the rice to get stuck to the bottom,
because the alternative is a kind of crust at the bottom of the pot
where the rice gets crispy, which tastes great in itself, but is
really bad mixed in with the rest of the rice in a sushi maki roll or
a piece of nigiri.

After the seven minutes have passed, you should turn the heat down
from max power to just enough power to let the rice simmer for an
additional fifteen minutes. Remember: Never take off the lid or you
will ruin the rice. After these last fifteen minutes, the rice is
cooked. But, it's definitely not done.

*** Optional: Let the rice cool down 

if you don't want it to get too sticky while you season it. The
trouble about cooling it down is that we don't want the rice to dry
out by leaving it on the kitchen table reacting with the air, and we
also want it to cool down rather quickly. A good tip is to use a
couple of clean kitchen towels dampened with cold water (not
wet!). Spread one on the table, spread the rice on top of it (remember
not to scrape the bottom, we don't want that half-burnt rice down
there in our sushi), and place the other towel on top of the rice, so
the air doesn't dry it up. This way, you should be able to cool the
rice in about an hour.

*** Make the su. 

For those interested, the word sushi is actually a compound of the
word su - which means vinegar - and the word shi - which means "skill
of hand". So, sushi basically means something like mastering the art
of vinegar. You need a good rice vinegar, some salt (please, coarse
salt, not fine, too many additives are put in this stuff to keep it
from clumping, and they don't taste very good!) and some
sugar. Because different brands of vinegar taste very different, it's
a good idea to sample your way through the process by tasting on it
along the way. But, a good rule of thumb says that for each 100
millilitres (3.4 fl.oz.) of vinegar, you'll need to add three
tablespoons of sugar and one-and-a-half teaspoon of salt. Put it all
in a pot and heat it up while stirring, until everything's
dissolved. Now, adjust the mixture by tasting it - too vinegary? Add
sugar. Not enough taste? Add salt. Not quite there? Add vinegar. Then
cool to room temperature.

***  Mix the su and rice. 

Traditionally, this is done with a hangiri, which is a round,
flat-bottom wooden tub or barrel, and a wooden paddle. Alternatively,
you can use a baking pan or cookie sheet (but not aluminum foil -
it'll react with the vinegar). You toss the rice gently with the su,
using a gentle chopping and flipping motion with a paddle, and let the
heat escape (if you haven't cooled the rice already). Otherwise, the
rice will continue cooking in its own heat. You can also spread the
rice so that it cools down faster, but be sure not to mash it!

1. Adjust to taste. Add a little su, then stir around (gently) with a wooden spatula or spoon, taste. Not enough? Repeat. You'll probably end up using somewhere between 100 and 250 millilitres of su for the portion we're making here. Remember not to try to get too much taste or saltiness out of the rice by adding su - the reason we don't use salt in the rice in the first place and don't want the su to make the rice salty is that sushi is dipped in soy sauce which is very salty indeed.
   

2. Use the sushi rice at room temperature. If the rice is still warm, cover it with a damp cloth (so it doesn't dry out) and leave it be until it reaches room temperature. Sushi tastes best when made from freshly cooked, unrefrigerated rice.



* White bread
:PROPERTIES:
:Cantidad: 1 loaf
:Tiempo: 3.5 horas
:Vegan: no
:Fuente: http://www.dinnerwithjulie.com/2012/03/04/julia-childs-white-sandwich-bread/
:END:

** Ingredientes

| 400 | g    | flour  |
|   4 | g    | yeast  |
| 1/2 | tbps | sugar  |
|   1 | tsp  | salt   |
|  30 | g    | butter |
| 300 | ml   | water  |

** Method

1. Pour 1/2 cup of the water into a bowl (preferably that of a stand
   mixer) and stir in the yeast and sugar. Let sit for 5 minutes, unit
   foamy. (If the yeast doesn't do anything, toss it out and buy fresh
   yeast.)
2. Add the rest of the water and about half of the flour. Stir until
   well blended. Add the rest of the flour, the salt and butter and
   stir with the dough hook (or by hand) until well combined and
   shaggy. Continue to knead (I let the dough hook go for about 8
   minutes, poking it down once in awhile) until it's smooth and
   elastic. You could do this by hand, too. If you used the dough
   hook, turn the dough out onto the countertop and knead a few times
   to make sure it's evenly smooth. 
3. Shape it into a ball and put it back into the bowl. Cover with a
   tea towel and let it sit for 1 - 1 1/2 hours, until it's doubled in
   size.
4. Butter one loaf pans. Punch the dough down (love that part!) and
   pat each piece into a rectangle that's about 9"x12" - or a bit
   bigger than a standard piece of paper.
5. Starting at a short end, fold it in thirds, like a letter. Place
   seam side down in the loaf pans, tucking the ends in. Cover with
   the tea towel again and leave them for an hour, until they puff
   right up out of the pan.
6. Preheat the oven to 190°C and put the rack in the middle of the
   oven. Bake for 30-35 minutes, until the loaves are honey
   brown. Immediately turn the loaves out of their pans and onto a
   rack to cool.

